name: GitHub CI

on: [push, pull_request]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm i --ignore-scripts
      - name: Lint code
        run: npm run lint

  test:
    needs: linter
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12, 14, 16, 17]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: npm install --ignore-scripts
    - name: Run tests
      run: npm run test:ci
